# Generated by Django 4.2.25 on 2025-11-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motry', '0002_seed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
