# Generated by Django 4.2.25 on 2025-11-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motry', '0004_uservehicle_post_user_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_vehicles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
